site_name: Phrasa Documentation

nav:
    - Getting Started: quickstart_sketch.md
    - Concepts: concepts.md
theme: 
    name: material
    favicon: img/favicon.ico
    palette:
        primary: 'purple'
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
