site_name: Phrasa Documentation

nav:
    - What is Phrasa?: index.md
    - Getting Started: getting_started.md
#    - Concepts:
#        - concepts.md
    - Instruments:
        - Synthesizers: synths.md
        - Samplers: samplers.md
theme: 
    name: material
    favicon: img/favicon.ico
    palette:
        primary: 'purple'
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
